version: '3.5'
services:
  es7:
    container_name: elasticsearch7
    build: docker/elasticsearch7/
    ulimits:
      memlock:
        soft: -1
        hard: -1    
    volumes:
      - ./docker/elasticsearch7/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - '9201:9200' # HOST:CONTAINER
      - '9301:9300'
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
    networks: 
      - api_network

  # OLD Kibana - tbd delete
  # kibana:
  #   build: docker/kibana/
  #   volumes:
  #     - ./docker/kibana/config/:/usr/share/kibana/config:ro
  #   ports:
  #     - '5601:5601'
  #   depends_on:
  #     - es7

  # NEW Kibana on es7
  # kibana7:
  #   image: docker.elastic.co/kibana/kibana:7.3.2
  #   container_name: kibana7
  #   ports:
  #     - '5601:5601'
  #   environment:
  #     ELASTICSEARCH_URL: http://localhost:9201
  #     ELASTICSEARCH_HOSTS: http://localhost:9201
  #   networks:
  #     - api_network

  redis:
    image: 'redis:4-alpine'
    container_name: redis
    ports:
      - '6379:6379'
    networks: 
      - api_network

volumes:
  esdat1:

# Networks are used to bridge and isolate services together https://docs.docker.com/network/bridge/
networks:
  api_network:
    driver: bridge