apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.nodejs.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: es7
  name: es7
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: es7
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.nodejs.yml
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: es7
    spec:
      containers:
      - env:
        - name: ES_JAVA_OPTS
          value: -Xmx512m -Xms512m
        - name: bootstrap.memory_lock
          value: "true"
        - name: cluster.name
          value: docker-cluster
        - name: discovery.type
          value: single-node
        image: revnite/vue-storefront-elasticsearch
        imagePullPolicy: ""
        name: elasticsearch7
        ports:
        - containerPort: 9200
        - containerPort: 9300
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
